AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/ExpandPathArguments:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false
